ktor:
  development: true
  deployment:
    port: "$PORT:8080"
    host:  0.0.0.0
  application:
    modules:
      - com.example.ApplicationKt.module
database:
  host: "$PGHOST:localhost"
  port: "$PGPORT:5535"
  name: "$PGDATABASE:cosmo"
  username: "$PGUSER:postgres"
  password: "$PGPASSWORD:1234"
  driver: org.postgresql.ds.PGSimpleDataSource
  poolSize: 3
