ktor:
  development: true
  deployment:
    port: "$PORT:8080"
  application:
    modules:
      - com.example.ApplicationKt.module
database:
  host: "$PGDATABASE:localhost"
  port: "$PGPORT:5535"
  name: "$PGDATABASE:cosmo"
  username: "$PGUSER:postgres"
  password: "$PGPASSWORD:1234"
